import { Header } from "app/components/shared/Header/Header";
import type { Metadata } from "next";
import 'app/sass/globals.sass'
import { Roboto } from 'next/font/google'
import { Footer } from "app/components/shared/Footer";

const roboto = Roboto({
  weight: ["100", "300", "500", "700"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
